### ISSUE TITLE
Wireframe Design HTML/CSS

### ISSUE THREAD

**Issue by jordanbaucke** [whiteboard-warriors/website#1]
HTML/Styles for HTML layout - working off redditblog design: https://redditblog.com/

- Responsive
- OpenSans Font

![2020-02-16_19-37-11](https://user-images.githubusercontent.com/354791/74621930-bdcfab00-50f3-11ea-99c6-9ec72131d689.png)
![2020-02-16_19-37-50](https://user-images.githubusercontent.com/354791/74621961-e5267800-50f3-11ea-8c38-ebd868e9c949.png)
![2020-02-16_19-38-13](https://user-images.githubusercontent.com/354791/74621964-e6f03b80-50f3-11ea-83fd-afbea5d05941.png)
![2020-02-16_19-20-15](https://user-images.githubusercontent.com/354791/74621993-02f3dd00-50f4-11ea-868c-f12c1418ddba.png)
<img width="857" alt="logo@2x" src="https://user-images.githubusercontent.com/354791/74670270-a88f6680-515d-11ea-96e3-9144af9741b7.png">

See Slack for Adobe Illustrator Vector art - want to keep it out of repo.

**Comment by jordanbaucke** [comment]
@pablomotta please see: https://drive.google.com/drive/folders/1nfCeBOuqMPnES0vK7HIZMQFENnjII06z?usp=sharing for AI version of the logo

**Comment by jordanbaucke** [comment]
@pablomotta checked out design looks great. Please open a pull-request to the main branch when you feel you're ready and we'll close this ticket and start opening individual ones

**Comment by rasreee** [comment]
Is this still open? I can share a draft in Figma to start on
