### ISSUE TITLE
Build Out Project Structure

### ISSUE THREAD

**Issue by jordanbaucke** [whiteboard-warriors/website#2]
Want to determine the project structure with React front-end and Python back-end.

- Single repository
- Frontend/backend folders? sub-repositories?
- Script to start localdev

**Backend**
Python Framework? 
1. Django
- Here is a [Django/React tutorial](https://scotch.io/tutorials/build-a-to-do-application-using-django-and-react)I found
2. Flask
3. Pyramid

**Frontend**
1. Do we want to use an "App" generator
2. Is anyone familiar with REDUX? Probably want to start more basic and build on it as we need more complex functionality

**Comment by leizleho** [comment]
Thinking of having this project structure:
```
website
  |.gitignore
  |.env
  |README.md
  |-- docs  (documentations)
  |-- deploys (deployment scripts)
  |-- src (source codes)
       |-- frontend
       |-- microservices
           |-- auth-service
           |-- cms-service
           |-- jobboard-service
           |-- social-service
```
Within this website repo, we add "src" directory for all the source code. Under src, we'll have frontend directory for the react app, and microservices for all services we will build.

**Comment by jordanbaucke** [comment]
@leizleho great! I love thinking about structuring the microservices early - I haven't built out this structure in python before however, so I'll be interested to learn more.
