### ISSUE TITLE
Login & Register Screens

### ISSUE THREAD

**Issue by jordanbaucke** [whiteboard-warriors/website#29]
We have two pull requests for login & register screens! I love the enthusiasm!

I want to leave it to you all to figure out what would work best for both and we'll combine. 

Please comment here about items we may want to take from each!!!

Jordan

https://github.com/whiteboard-warriors/website/pull/28
https://github.com/whiteboard-warriors/website/pull/27

**Comment by leizleho** [comment]
We can close this issue. We'll use @spenceruns PR. He's using reactstrap which is being used the whole team.

**Comment by spenceruns** [comment]
I'll be adding the validation to the login/signup modal within the next day or two. Let me know when the backup is somewhat up and running and I can help with connecting the modal to it!
