### ISSUE TITLE
Change "Linked In" to "LinkedIn" (Profile Completeness Notification)

### ISSUE THREAD

**Issue by jordanbaucke** [whiteboard-warriors/website#64]
<img width="1318" alt="2021-05-26_16-50-08" src="https://user-images.githubusercontent.com/354791/119745213-8a291800-be42-11eb-810c-fce5ff0654cd.png">

**Comment by pablomotta** [comment]
Fixed alert coming from Components/scene/Jobs/JobCard/index.js
