### ISSUE TITLE
Forgot Password Page

### ISSUE THREAD

**Issue by jordanbaucke** [whiteboard-warriors/website#65]
- Remember not to reveal if the requested email is in the database
- _This is lower priority for now_ Because this form generates an email a possible security vulnerability is bots submitting emails (at the very least this could spike our email delivery bill), so a [captcha](https://developers.google.com/recaptcha?authuser=2) should be implemented

<img width="1318" alt="2021-05-26_16-51-51" src="https://user-images.githubusercontent.com/354791/119745353-cc525980-be42-11eb-86e7-c7bd22a02032.png">

**Comment by pablomotta** [comment]
Completed and tested.
